substitutions:
  friendly_name: JXD-R6-E1ETH
  device_description: JXD-R6-E1ETH v1
# Production firmware

# only for display version
#packages:
#  display: !include includes/jxd-display.yaml

esphome:
  name: jxd-r6-e1eth
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2025.3.3
  on_boot:
    priority: 600
    then:
      - pcf8563.read_time:
          id: pcf8563_time
      - delay: 10min
      - if:
          condition:
            lambda: return id(init_in_progress);
          then:
            - lambda: id(init_in_progress) = false;
            - switch.turn_on: status_led


esp32:
  board: esp32dev
  flash_size: 8MB
  framework:
      type: esp-idf
      version: latest
      # Custom sdkconfig options
      sdkconfig_options:
        CONFIG_COMPILER_OPTIMIZATION_SPEED: y


time:
# Real time clock PCF8563
  - platform: pcf8563
    id: pcf8563_time
    address: 0x51
    timezone: Europe/Moscow
    # update_interval: 15 min
# get time from ntp
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
# sync ntp time to RTC
    on_time_sync:
      then:
        pcf8563.write_time:

api:
  id: api_id

ota:
  - platform: esphome
    id: ota_esphome

psram:
  mode: octal
  speed: 80MHz


globals:
  # Global initialization variable. Initialized to true and set to false once everything is connected. Only used to have a smooth "plugging" experience
  - id: init_in_progress
    type: bool
    restore_value: no
    initial_value: 'true'

# Enable logging
logger:
  # level: VERBOSE
  # ethernet: debug
  level: debug
  logs:
    text_sensor: NONE
    sensor: NONE
    # componet.display: NONE

# Enable built-in web server
web_server:
  port: 80
  version: 3

# Enable WiFi connection
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   reboot_timeout: 0s

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

text_sensor:
# for Wifi use wifi_info
  # - platform: wifi_info
  #   ip_address:
  #     name: "Wifi IP"
  #     id: ip
  #   mac_address:
  #     name: ESP Mac Wifi Address
  #     id: mac1

# for Ethernet use ethernet_info
  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: IP
        id: ip
      on_value:
        then:
          - lambda: id(init_in_progress) = false;
          - switch.turn_off: status_led
    mac_address:
      name: MAC
      id: mac1


# uart:
#   tx_pin: GPIO33
#   rx_pin: GPIO34
#   baud_rate: 9600

#   debug:
#     direction: BOTH
#     dummy_receiver: true
#     #after:
#     #  delimiter: "\n"
#     sequence:
#       - lambda: UARTDebug::log_string(direction, bytes);
#       - uart.write: 'Hello World' 


i2c:
  sda: 5
  scl: 4
  # for display better to use 800kHz, fixes warnings
  frequency: 800kHz
  scan: true
  id: i2c1

#GPIO expander
pca9554:
  - id: jxd_d6_r6_exp
    pin_count: 16
    address: 0x22

one_wire:
  platform: gpio
  pin: GPIO15
  # update_interval: 3s

# Push button for green leds blink 3 times
button:
  - platform: template
    name: "Identify"
    on_press:
      - repeat:
          count: 3
          then:
            - switch.turn_on: status_led
            - delay: 0.5s
            - switch.turn_off: status_led
            - delay: 0.5s

# show first available 1-wire sensor if address empty
sensor:
  - platform: dallas_temp
    name: "1-WIRE TEMPERATURE"
#    address: "0xXXXXXXXXXXXXX"

# VIN measure
  - platform: adc
    pin: GPIO35
    attenuation: 2.5dB
    accuracy_decimals: 2
    filters:
      - multiply: 32.0
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 10
      - calibrate_polynomial:
          degree: 3
          datapoints:
            - 8.76 -> 9.0
            - 11.72 -> 12.0
            - 15.56 -> 16.0
            - 23.36 -> 24.0
            - 29.28 -> 30.0
      - clamp:
          min_value: 0
      - lambda: |-
          if (x <=2.8) return 0;
          return x;

    name: "VIN voltage"
    id: vin_meas
    update_interval: 100ms

  - platform: adc
    pin: GPIO37
    attenuation: 2.5dB
    accuracy_decimals: 2
    filters:
      - multiply: 32.0
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 10
      - calibrate_polynomial:
          degree: 3
          datapoints:
            - 8.76 -> 9.0
            - 11.72 -> 12.0
            - 15.56 -> 16.0
            - 23.36 -> 24.0
            - 29.28 -> 30.0
      - clamp:
          min_value: 0
      - lambda: |-
          if (x <=2.8) return 0;
          return x;
    name: "PoE voltage"
    update_interval: 100ms

# board temperature sensor
  - platform: tmp102
    name: "PCB TEMPERATURE"
    update_interval: 20s

switch:
  - platform: gpio
    name: "Status led"
    id: status_led
    pin: GPIO2
# Relay 1
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    pin:
      pca9554: jxd_d6_r6_exp
      number: 0
      mode:
        output: true
      inverted: false
# relay 2
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    pin:
      pca9554: jxd_d6_r6_exp
      number: 1
      mode:
        output: true
      inverted: false
# relay 3
  - platform: gpio
    name: "Relay 3"
    id: relay_3
    pin:
      pca9554: jxd_d6_r6_exp
      number: 2
      mode:
        output: true
      inverted: false
# relay 4
  - platform: gpio
    name: "Relay 4"
    id: relay_4
    pin:
      pca9554: jxd_d6_r6_exp
      number: 3
      mode:
        output: true
      inverted: false
# relay 5
  - platform: gpio
    name: "Relay 5"
    id: relay_5
    pin:
      pca9554: jxd_d6_r6_exp
      number: 4
      mode:
        output: true
      inverted: false
# relay 6
  - platform: gpio
    name: "Relay 6"
    id: relay_6
    pin:
      pca9554: jxd_d6_r6_exp
      number: 5
      mode:
        output: true
      inverted: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "FN button"
    id: fn_button
# input 1
  - platform: gpio
    name: "Input 1"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 8
      mode:
        input: true
      inverted: false
# input 2
  - platform: gpio
    name: "Input 2"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 9
      mode:
        input: true
      inverted: false
# input 3
  - platform: gpio
    name: "Input 3"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 10
      mode:
        input: true
      inverted: False
# input 4
  - platform: gpio
    name: "Input 4"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 11
      mode:
        input: true
      inverted: false
# input 5
  - platform: gpio
    name: "Input 5"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 12
      mode:
        input: true
      inverted: false
# input 6
  - platform: gpio
    name: "Input 6"
    pin:
      pca9554: jxd_d6_r6_exp
      number: 13
      mode:
        input: true
      inverted: false
